### ISSUE TITLE
Cannot build the test_coins package

### ISSUE THREAD

**Issue by ghost** [OmniBTC/Sui-AMM-swap#3]
- My trouble: after building and publishing the swap package successed, I replace the swap address in the test_coins package before building it
Here is the error message after I ran ```sui move build```

Failed to build Move modules: Unable to resolve packages for package 'test-coins'

Caused by:
    0: Unable to resolve named address 'swap' in package 'test-coins' when resolving dependencies
    1: Attempted to assign a different value '0x772151a95c203eada2d01329df5fa8a15875d670' to an a already-assigned named address '0x0'.

- My machine:
	+ Ubuntu 20.04
	+ Sui version: devnet-19.0

**Comment by icodezjb** [comment]
Use latest code(commit 7dcbc289f9a1b4f315c3ee6f6b1da3f0254b5289):
- (1). deploy swap 
- (2). replace real swap address for test_coins in swap Move.toml file
- (3). deploy test_coins
